openapi: 3.0.0
info:
  title: Online Bookstore API
  description: A simple RESTful API for an online bookstore
  version: 1.0.0
servers:
  - url: http://localhost:3000
    description: Development server
paths:
  /api/books:
    get:
      summary: List books
      responses:
        '200':
          description: A list of books
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Book'
    post:
      summary: Create a new book
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateBookRequest'
      responses:
        '201':
          description: Book created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Book'
        '400':
          description: Bad request - missing required fields
  /api/books/{id}:
    get:
      summary: Get book details by ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Book details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Book'
        '404':
          description: Book not found
components:
  schemas:
    Book:
      type: object
      properties:
        id:
          type: string
          example: "1"
        title:
          type: string
          example: "The Great Gatsby"
        author:
          type: string
          example: "F. Scott Fitzgerald"
        genre:
          type: string
          example: "Classic"
        isbn:
          type: string
          example: "9780743273565"
        description:
          type: string
          example: "A story of wealth, love, and the American Dream in the 1920s."
    CreateBookRequest:
      type: object
      required:
        - title
        - author
        - genre
        - isbn
      properties:
        title:
          type: string
          example: "New Book Title"
        author:
          type: string
          example: "Author Name"
        genre:
          type: string
          example: "Fiction"
        isbn:
          type: string
          example: "1234567890123"
        description:
          type: string
          example: "A description of the new book."